Traceback (most recent call last):
  File "downloadbg.py", line 36, in <module>
  File "downloadbg.py", line 29, in downloadpic
IOError: [Errno 2] No such file or directory: 'D:\\git\\bingbg\\dist\\image\\bing20170818.jpg'
Traceback (most recent call last):
  File "downloadbg.py", line 36, in <module>
  File "downloadbg.py", line 29, in downloadpic
IOError: [Errno 2] No such file or directory: 'D:\\git\\bingbg\\dist\\image\\bing20170818.jpg'
Traceback (most recent call last):
  File "downloadbg.py", line 36, in <module>
  File "downloadbg.py", line 29, in downloadpic
IOError: [Errno 2] No such file or directory: 'D:\\git\\bingbg\\dist\\image\\bing20170818.jpg'
Traceback (most recent call last):
  File "downloadbg.py", line 36, in <module>
  File "downloadbg.py", line 29, in downloadpic
IOError: [Errno 2] No such file or directory: 'D:\\git\\bingbg\\dist\\image\\bing20170818.jpg'
Traceback (most recent call last):
  File "downloadbg.py", line 36, in <module>
  File "downloadbg.py", line 29, in downloadpic
IOError: [Errno 2] No such file or directory: 'D:\\git\\bingbg\\dist\\image\\bing20170818.jpg'
Traceback (most recent call last):
  File "downloadbg.py", line 40, in <module>
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 157, in makedirs
WindowsError: [Error 123] : 'D:\\git\\bingbg\\distE:'
Traceback (most recent call last):
  File "downloadbg.py", line 40, in <module>
  File "os.pyc", line 150, in makedirs
  File "os.pyc", line 157, in makedirs
WindowsError: [Error 123] : 'D:\\git\\bingbg\\distE:'
